# ===== Configuration de la base de donnees PostgreSQL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/myspace_db
spring.datasource.username=postgres
spring.datasource.password=azizaziz
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== Configuration Hibernate / JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== Configuration du serveur =====
server.port=8081

# ===== Logs =====
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.open-in-view=false
# ===== Configuration JWT =====
app.jwt.secret=myspace-secret-key-super-longue-pour-la-signature-hs256-2026-projet-universitaire
app.jwt.expiration-ms=3600000

# Configuration Spring Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=azizbouchriha2@gmail.com
spring.mail.password=sffcrebdbiaxgydh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true